services:
  moontv-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moontv-core
    restart: unless-stopped
    environment:
      - USERNAME=admin
      - PASSWORD=13899989701
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks
      - KVROCKS_URL=redis://moontv-kvrocks:6666
      - SITE_BASE=https://tv.rondive.com
      - NEXT_PUBLIC_SITE_NAME=Rondive TV
      - NODE_ENV=production
      - FFMPEG_PATH=/usr/bin/ffmpeg
    depends_on:
      - moontv-kvrocks
    ports:
      - "3100:3000"

  moontv-kvrocks:
    image: apache/kvrocks
    container_name: moontv-kvrocks
    restart: unless-stopped
    volumes:
      - kvrocks-data:/var/lib/kvrocks

volumes:
  kvrocks-data:
